//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MimatAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_institution
    {
        public int id { get; set; }
        public string institution { get; set; }
        public string mail { get; set; }
        public string password { get; set; }
        public string created_at { get; set; }
        public System.DateTime last_login { get; set; }
    }
}
