//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MimatAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MimatEntities : DbContext
    {
        public MimatEntities()
            : base("name=MimatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin_institution> admin_institution { get; set; }
        public virtual DbSet<workstation_classrooms> workstation_classrooms { get; set; }

        public System.Data.Entity.DbSet<MimatAPI.Models.ViewModel.WorkstationClassrooms> WorkstationClassrooms { get; set; }
    }
}
