//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MimatAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class workstation_classrooms
    {
        public int id { get; set; }
        public string model { get; set; }
        public string cpu { get; set; }
        public string classroom { get; set; }
        public string location { get; set; }
        public int inSafeArea { get; set; }
        public System.DateTime lastUpdate { get; set; }
    }
}
